FROM ts-zsh-dev

USER root
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 소스 코드 clone
RUN git clone https://github.com/jpyo0803/gomoku.git /app

# workspace별 npm install
WORKDIR /app/packages/gomoku-core
RUN npm install

WORKDIR /app/packages/gomoku-backend
RUN npm install
RUN npm run build

CMD ["npm", "run", "start:dev"]