version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gomoku
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gomoku-net

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    networks:
      - gomoku-net

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - "8080:8080"
    networks:
      - gomoku-net

volumes:
  db-data:

networks:
  gomoku-net:
    driver: bridge
